#!/usr/bin/env bash


if [ -z "$LD_LIBRARY_PATH" ]
then
    export LD_LIBRARY_PATH=~/.saite/Libs
else
    export LD_LIBRARY_PATH=~/.saite/Libs:$LD_LIBRARY_PATH
fi

#echo $LD_LIBRARY_PATH

/usr/bin/nohup java \
               --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED \
               --add-opens=java.base/sun.nio.ch=ALL-UNNAMED \
               -cp SAITEDIR/resources:SAITEDIR/aerial.aerosaite-VERSION-standalone.jar aerial.aerosaite.core \
               --port 3000 --repl-port 4100 > start.log &
